# Site settings
title: BUILDS
email: acm@bu.edu
description: Office of Undergraduate Hacking

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EF5350 #80B3FF
  secondary: 212121 #FD6E8A
  
header-image: url("img/bg.jpg")

# Footer settings
footer:
  copyright: BUILDS 2014
  poweredby: <a href="http://startbootstrap.com">Start Bootstrap</a> and <a href="http://jekyllrb.com">jekyll</a>
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/_hackerspace
  - title: facebook
    url: https://www.facebook.com/groups/acmbuilds/
  - title: github
    url: https://github.com/BUILDS-

# Postal address (add as many lines as necessary)
address:
  - line: 111 Cummington Mall, Room B26
  - line: Boston, MA 02215

# Build settings
markdown: kramdown
permalink: pretty
