# Site settings
# title: BUILDS
# email: acm@bu.edu
# description: > # this means to ignore newlines until "baseurl:"
  # BUILDS is a student-run Boston University hackerspace
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# markdown: kramdown

name: BUILDS
highlighter: rouge
exclude: [README.md, _scripts, Gemfile, Gemfile.lock]
plugins: ./_plugins
base: "http://builds.cc"
paginate_path: "events/page:num"
paginate: 5
